creation of the billing details part, where various inputs and texts …
javierbarbozam/proyecto_final_web pull request #2
Opened 2022-11-30 08:31 UTC by juanCsacasa

…are added

2022-11-30 21:44 UTC, javierbarbozam requested changes, later dismissed
Mae ya están listos mis comentarios, me avisa si me di a entender en todo

2022-11-30 21:44 UTC, javierbarbozam commented on payment/payment.html
> +      <h2>Billing details</h2>
Mae, esto ponelo como h1, porque el logo va a ser texto con estilos nada más.

2022-11-30 21:44 UTC, javierbarbozam commented on payment/payment.html
> +        <label for="ID number"><input type="text" placeholder="ID Number" name="ID Number" class="payment-form__input"></label>
Mae, el input necesita un atributo ID, que es el que va a vincularse con el for del Label, y acordate que va sin espacios.. "last-name" por ejemplo

2022-11-30 21:44 UTC, javierbarbozam commented on payment/payment.html
> +        <select name="City" class="payment-form__input">
Mae el select también necesita atributo ID para vincularlo al Label

2022-11-30 21:44 UTC, javierbarbozam commented on payment/payment.html
> +          <option value="Paises bajos">Paises bajos</option>
Mae, estábamos pensando en que tal vez los value de los options del select puedan ser numéricos, recuerdo que Leiva nos hizo un comentario sobre eso el cuatri pasado.. entonces seria algo como

`<option value="1">Costa Rica</option>`

2022-11-30 21:49 UTC, Heylin-Loaiza submitted a review, later dismissed
En general, podés poner todos los atributos de las etiquetas en minúscula porfa, cualquier duda que tengas me decís

2022-11-30 21:49 UTC, Heylin-Loaiza commented on payment/payment.html
> +        <label for="Name"><input type="text" placeholder="Name" name="Name" class="payment-form__input"></label>
Juan podes por fa sacar los inputs para separarlos de los labels?
```
<label></label>
<input>
```
De esta forma

2022-11-30 21:49 UTC, Heylin-Loaiza commented on payment/payment.html
> +        <label for="Last name"><input type="text" placeholder="Last Name" name="Last name" class="payment-form__input"></label>
También, podrías cambiar el atributo name="" por minúsculas, por ejemplo name="last-name" o name="id-number"

2022-12-01 22:50 UTC, javierbarbozam approved these changes

2022-12-01 22:50 UTC, merged